console.log(3 + 5);
console.log(95 - 15);
console.log(3 * 5);
console.log(80 / 4);
console.log(28 % 5);
console.log((3 + 2) * (6 -3));
var nombre = "Roberto";
var apellido = "Lopez";
var completo = nombre + " " + apellido;
console.log(completo);